### ISSUE TITLE
[Auto]（2023 年，如何学习编程并找到一份开发工作）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#1044]
- 原文网址：[How to Learn to Code & Get a Developer Job in 2023 [Full Book]](https://www.freecodecamp.org/news/learn-to-code-book/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/learn-to-code-book.md

**Comment by luojiyin1987** [comment]
怎么分工？

**Comment by PapayaHUANG** [comment]
@miyaliu666 我可以参与一部分，所以同问怎么分工

**Comment by miyaliu666** [comment]
@luojiyin1987 @PapayaHUANG  你们可以商量一下，各自翻译哪部分。在本地翻译之后，由一个人汇集全部译文，提交到这里。然后在专栏和公众号发文的时候，可以同时写两个作者。这个方法可以吗？

**Comment by PapayaHUANG** [comment]
两个人分的话任务量太大了诶，可以号召到更多人参与进来吗？

**Comment by miyaliu666** [comment]
我发到群里了，还是等大家看到了自己愿意来认领吧。要不你们先看看想翻哪部分吧，我也可以翻一些。

**Comment by miyaliu666** [comment]
Quincy 还会继续添加英文内容，尽量完善这本指南，所以我们也慢慢进行翻译吧。

**Comment by YeSuX** [comment]
我也可以参与翻译，请问一下该如何分工呢

**Comment by dake0913** [comment]
我来啦，我也可以参与，建议 @luojiyin1987 和 @PapayaHUANG 来分工，我可以每周抽出4-6小时来翻译。

**Comment by miyaliu666** [comment]
Quincy 这周会增加更多内容，请大家暂时不要翻译，等他定稿后再翻译。我稍后会更新 Markdown 文件。谢谢！

**Comment by miyaliu666** [comment]
已经有几位译者认领翻译这本书，稍后大家会创建 PR。

**Comment by dake0913** [comment]
https://github.com/freeCodeCamp/chinese/pull/1076  line228-455#1076
