### ISSUE TITLE
[Auto]（如何录制播客）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#1077]
- 原文网址：[How to Start a Podcast - A Step-By-Step Guide to Recording and Publishing](https://www.freecodecamp.org/news/a-month-ago-i-knew-nothing-about-podcasting-50-000-downloads-later-heres-what-i-ve-learned-2d7082a28f27)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/a-month-ago-i-knew-nothing-about-podcasting-50-000-downloads-later-heres-what-i-ve-learned-2d7082a28f27.md

**Comment by miyaliu666** [comment]
@luojiyin1987 @stevending1st 有空帮忙看一下为什么这个 issue 创建失败呢，谢谢

**Comment by luojiyin1987** [comment]
@miyaliu666    重新爬了， 成功了

**Comment by miyaliu666** [comment]
好啦，谢谢两位！
