### ISSUE TITLE
How to build sturdy React apps with TDD and the React Testing Library

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#108]
文章：[How to build sturdy React apps with TDD and the React Testing Library](https://www.freecodecamp.org/news/how-to-build-sturdy-react-apps-with-tdd-and-the-react-testing-library-47ad3c5c8e47/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/how-to-build-sturdy-react-apps-with-tdd-and-the-react-testing-library.md)
PR 地址：

**Comment by herosql** [comment]
@miyaliu666
