### ISSUE TITLE
[Auto]（JavaScript 中如何生成指定范围内的随机数）

### ISSUE THREAD

**Issue by xgqfrms** [freeCodeCamp/chinese#1113]
- 原文网址：[How to Generate a Random Number within Certain a Range in JavaScript](https://www.freecodecamp.org/news/generate-random-number-within-a-range-in-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/generate-random-number-within-a-range-in-javascript.md

**Comment by Jiajun-Jiao** [comment]
I want to claim this issue. I've started working on the translation.
