### ISSUE TITLE
[Auto]（如何创建并发布一个 Vue 组件库）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/chinese#1152]
- 原文网址：[原文标题](https://www.freecodecamp.org/news/how-to-create-and-publish-a-vue-component-library-update/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-create-and-publish-a-vue-component-library-update.md

**Comment by xgqfrms** [comment]
I would like to translate this article.

**Comment by luojiyin1987** [comment]
> I would like to translate this article.

OK
