### ISSUE TITLE
[Auto]（响应式网页设计--如何让网站在手机和平板电脑上看起来更美观）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#1169]
- 原文网址：[Responsive Web Design – How to Make a Website Look Good on Phones and Tablets](https://www.freecodecamp.org/news/responsive-web-design-how-to-make-a-website-look-good-on-phones-and-tablets)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/responsive-web-design-how-to-make-a-website-look-good-on-phones-and-tablets.md

**Comment by miyaliu666** [comment]
@luojiyin1987 可以帮忙看一下这个 issue 吗？为什么说 route 不一致？

[这个](https://github.com/freeCodeCamp/chinese/issues/420#issuecomment-1655757045)是我之前创建的，404 了，所以我想重新建一个。

**Comment by luojiyin1987** [comment]
@miyaliu666    freecodecamp 网站做的重定向导致的

**Comment by miyaliu666** [comment]
哦哦，不过这个没有 404 了 @luojiyin1987 

Hi @herosql 如果你想翻译这篇文章的话，可以在这个 issue 提交 PR 啦，我看了 markdown 文件是正常显示的，谢谢：）

**Comment by miyaliu666** [comment]
repeated article：https://github.com/freeCodeCamp/chinese/pull/257
