### ISSUE TITLE
[Auto]（如何使用 ChatGPT API 创建聊天机器人）

### ISSUE THREAD

**Issue by Jiajun-Jiao** [freeCodeCamp/chinese#1172]
- 原文网址：[How to Create a Chatbot With the ChatGPT API](https://www.freecodecamp.org/news/how-to-create-a-chatbot-with-the-chatgpt-api/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-create-a-chatbot-with-the-chatgpt-api.md

**Comment by Jiajun-Jiao** [comment]
I want to claim this issue. I've started working on the translation.

**Comment by tianheg** [comment]
You should add a new label `Translation-in-progress`, remove the old one

**Comment by Jiajun-Jiao** [comment]
> You should add a new label `Translation-in-progress`, remove the old one

Thank you @tianheg for your suggestion, but unfortunately I don't have permission to change the label. The previous one was auto-generated.
