### ISSUE TITLE
[Auto]（如何使用 Three.js 在 React.js 应用程序中实现一个 Blender 模型）

### ISSUE THREAD

**Issue by xgqfrms** [freeCodeCamp/chinese#1175]
- 原文网址：[原文标题](https://www.freecodecamp.org/news/blender-three-js-react-js/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/blender-three-js-react-js.md

**Comment by xuxuecho** [comment]
@miyaliu666 已完成翻译
