### ISSUE TITLE
[Auto]如何使用 .github 仓库

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp/chinese#1183]
- 原文网址：[How to Use the .github Repository](https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-use-the-dot-github-repository.md

**Comment by ProjektMing** [comment]
抱歉，我想尝试着帮忙翻译一下的，但是初次使用pr，不知是哪一步出的错：
首先我点了md文件，要求fork才能修改，我fork后按教程加入ID后提交，然而跳转的新页面并不是教程所指的pr，而是停在了commit，我在提交里评论关闭议题理所当然的没有用，并且我也没法直接新建一次拉取请求。
希望能够解释一下这个机制。

**Comment by ProjektMing** [comment]
@miyaliu666 我想我应该是完成了，代码的英文部分应该不需要翻译吧？😕 （我也可能多建了两个分支？我不知道在哪里，也不知道怎么删掉）

**Comment by TechQuery** [comment]
> @miyaliu666 我想我应该是完成了，代码的英文部分应该不需要翻译吧？😕 （我也可能多建了两个分支？我不知道在哪里，也不知道怎么删掉）

代码里的注释部分还是翻译一下。

你新建的分支都在你 fork 的仓库里，合并后你可以把整个仓库删掉就行。

**Comment by miyaliu666** [comment]
@ProjektMing 谢谢你帮忙翻译，我最近在做别的任务，在这里的回复会慢一点，抱歉。我看到你提交 PR 的方式是对的，我会尽快校对内容。
