### ISSUE TITLE
[Auto]（JavaScript Promises 工作原理--初学者手册）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#1208]
[How JavaScript Promises Work – Handbook for Beginners](https://www.freecodecamp.org/news/the-javascript-promises-handbook/)

**Comment by James-Z-Zhang00** [comment]
@miyaliu666 你好，我可以负责翻译这篇文章吗？

**Comment by miyaliu666** [comment]
> @miyaliu666 你好，我可以负责翻译这篇文章吗？

@James-Z-Zhang00 可以的，谢谢你参与翻译。你可以根据这个仓库 readme 中的图文指南创建 PR。

**Comment by James-Z-Zhang00** [comment]
> > @miyaliu666 你好，我可以负责翻译这篇文章吗？
> 
> 
> 
> @James-Z-Zhang00 可以的，谢谢你参与翻译。你可以根据这个仓库 readme 中的图文指南创建 PR。

@miyaliu666 我看到这个点进去可以直接编辑文件然后 commit。是不是创建PR有其他的好处。可以解释一下吗
