### ISSUE TITLE
[Auto] 用异步生成器代替状态管理

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp/chinese#1242]
[Async Generators as an alternative to State Management](https://www.freecodecamp.org/news/async-generators-as-an-alternative-to-state-management/)

**Comment by ProjektMing** [comment]
该文章似乎在fCC上已有翻译：[《使用 Async Generators 替代状态管理》](https://www.freecodecamp.org/chinese/news/async-generators-as-an-alternative-to-state-management)？
虽然有些许不同，但真的需要更改吗？（不过当时是原创转载的，大概因此没有记录）

**Comment by TechQuery** [comment]
> 该文章似乎在fCC上已有翻译：[《使用 Async Generators 替代状态管理》](https://www.freecodecamp.org/chinese/news/async-generators-as-an-alternative-to-state-management)？ 虽然有些许不同，但真的需要更改吗？ Duplicate as #8 ?

因原任务的源文件是 @jingruzhang 在 632bad6 手工添加，且文件名与 URL 路径不对应，导致我再次添加时 GitHub action 中的爬虫找不到同名文件而不报错、中止，使我成功添加这篇文章。
