### ISSUE TITLE
Why You Need to Understand Software Requirements as a Software Engineer 你以为软件工程师就是写代码的吗？深入理解软件需求很重要！

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#198]
文章：[Why You Need to Understand Software Requirements as a Software Engineer 你以为软件工程师就是写代码的吗？深入理解软件需求很重要！](https://www.freecodecamp.org/news/build-a-simple-json-api-in-python/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/why-understanding-software-requirements-matter-to-you-as-a-software-engineer.md)
PR 地址：

**Comment by thirteens** [comment]
closes #198
