### ISSUE TITLE
CSS Shapes Explained: How to Draw a Circle, Triangle, and More Using Pure CSS 通过绘制图形实例详解 CSS shape

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#213]
文章：[CSS Shapes Explained: How to Draw a Circle, Triangle, and More Using Pure CSS 通过绘制图形实例详解 CSS shape](https://www.freecodecamp.org/news/css-shapes-explained-how-to-draw-a-circle-triangle-and-more-using-pure-css/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/css-shapes-explained-how-to-draw-a-circle-triangle-and-more-using-pure-css.md)
PR 地址：

**Comment by suiboyu** [comment]
# **解释CSS形状：如何使用纯CSS绘制圆，三角形等**

**Thomas Weibenfalk**
开发人员和设计师对React.js充满热情，课程创建者，老师，企业家和数字原生用户

在我们开始之前。如果你想获得更多免费内容和使用视频格式。千万不要错过我的YouTube频道，在这里我每周发布有关FrontEnd编码的视频。

https://www.youtube.com/user/Weibenfalk
----------

你是Web开发和CSS的新手吗？你是否想过如何在互联网上看到那些漂亮的形状？别再奇怪了。你来对地方了。

下面，我将解释使用CSS创建形状的基本知识。关于这个话题有**很多**要告诉你的！因此，我不会涵盖所有（绝大部分）工具和形状，但这应该使你基本了解如何使用CSS创建形状。

一些形状比其他形状需要更多的“技巧和窍门”。使用CSS创建形状通常是使用**宽度，高度，顶部，右侧，左侧，边框，底部，变换**和伪元素（例如：before和：after）的组合。我们还具有更现代的CSS属性，可使用诸如**shape-outside**和**clip-path**之类的形状来创建形状。我也会在下面写它们。

## CSS形状-基本方法
通过CSS使用一些技巧，我们一直都能够创造出像正方形， 圆，三角形这样的基本形状。现在让我们看看其中的一些。

### 正方形和矩形
正方形和矩形可能是最容易实现的形状。默认情况下，div 始终是正方形或矩形。

如下面的代码所示，设置宽度和高度。然后，只需为元素提供背景色即可。你可以在元素上具有任何其他想要的属性。

### 圆
创建圆几乎一样容易。要创建一个圆，我们可以在元素上设置边框半径。这将在元素上创建弯曲的角。

如果将其设置为50％，将创建一个圆。如果你设置不同的宽度和高度，我们将得到一个椭圆形。

### 三角形
三角形有点棘手。我们必须在元素上设置边框以匹配三角形。通过将元素的宽度和高度设置为零，元素的实际宽度将成为边框的宽度。

请记住，元素的边界边缘彼此成45度对角线。这就是为什么此方法可以创建三角形的原因。通过将其中一个边界设置为纯色，而将其他边界设置为透明，它将采用三角形的形式。

如果要使三角形/箭头指向另一个方向，则可以更改与要显示的那一侧相对应的边框值。或者，如果你真的想花哨的话，可以使用transform属性旋转元素。

好了- 这是CSS基本形状的简介。你可能会想出无数种形状。这些只是基础知识，但只要有一些创造力和决心，仅凭基本的CSS属性就可以实现很多目标。

在某些情况下，使用更高级的形状时，最好使用：after和：before伪选择器。这超出了本文的范围，因为我的意图是涵盖使你入门的基础知识。

### 坏处
**上述方法有一个很大的缺点**。例如，如果你希望文本四处流动并包裹形状。具有背景和边框以构成形状的常规 HTML div 不允许这样做。文本将不会适应你的形状，并且不会围绕你的形状流动。相反，它将围绕div本身（是正方形或矩形）流动。

下图显示了三角形以及文本如何流动。

幸运的是，我们可以使用一些现代CSS属性来代替。

### CSS形状-另一种方法
如今，我们有一个名为**shape-outside**的属性可在CSS中使用。此属性使你可以定义文本将包裹/流动的形状。

除了这个属性，我们还有一些基本形状：

**inset（）
circle（）
ellipse（）
多边形（）**

**提示**：你还可以使用**clip-path**属性。你可以用相同的方式创建形状，但是不会像外部形状那样使文本环绕形状。

我们将要使用shape-outside属性将形状应用到的元素必须是浮动的。它还必须具有定义的宽度和高度。**知道这一点非常重要！**

你可以在此处详细了解原因。以下也是我从提供的developer.mozilla.org链接中获取的文本。

> shape-outside使用下面列表中的值指定该属性，这些值定义了float元素的浮动区域。浮动区域确定内联内容（浮动元素）环绕的形状。

### inset（）
inset（）类型可用于创建一个矩形/正方形，并为环绕文本提供可选的偏移量。它允许你提供有关你的环绕文本要与形状重叠多少的值。

你可以将所有四个方向的偏移量指定为相同的：**inset（20px）**。或者可以为每个方向分别设置：**inset（20px 5px 30px 10px）**。

你还可以使用其他单位来设置偏移量，例如百分比。这些值的对应关系如下：**inset（右上左下）。**

查看以下代码示例。我已将插入值指定为顶部20px，右侧5px，底部30px和左侧10px。如果你希望文本围绕正方形显示，则可以完全跳过inset（）。而是在div上设置背景并照常指定大小。

文本偏移指定的值。在这种情况下，顶部20像素，右侧5像素，底部30像素，左侧10像素
还可以给inset（）一个第二个值，该值指定插图的边界半径。如下所示：

###  圆
在这个图中，使用**shape-outside**属性创建了一个圆。你还必须应用具有相应属性的**剪切路径**，才能显示圆。

所述剪切路径属性可以取相同的值作为形状外属性，以便我们可以给它的 circle（），我们使用的形状形状外。另外，请注意，我在此处的元素上应用了20px的边距，为文本提供了一些空间。

在上面的示例中，我没有指定圆的半径。这是因为我希望它与div一样大（300px）。如果要为圆指定不同的大小，则可以这样做。

circle（）采用两个值。第一个值是半径，第二个值是位置。这些值将指定圆的中心。

在下面的示例中，我将半径设置为50％。然后，我将圆心偏移了30％。注意，在半径和位置值之间必须使用单词“ at”。

我还在剪切路径上指定了另一个位置值。当我将位置移到零时，这会将圆圈切成两半。

### 椭圆
椭圆的工作方式与圆形相同，只不过它们创建了一个椭圆。你可以定义X值和Y值，如下所示：ellipse（25px 50px）。

与圆形相同，它也将位置值作为最后一个值。

### 多边形
多边形是定义了不同顶点/坐标的形状。在下面，我创建一个“ T”形，这是我名字中的第一个字母。我从0,0坐标开始，并从左向右移动以创建“ T”形。

### 图片
你还可以使用具有透明背景的图像来创建形状。像下面这轮美丽的月亮。

这是具有透明背景的.png图像。

就是这样！感谢您的阅读。

关于本文的作者
我叫Thomas Weibenfalk，是瑞典的一名开发者。我会定期在我的YouTube频道上创建免费教程。在React和Gatsby上还有一些高级课程。随时通过以下链接访问我：

Twitter的- @weibenfalk，
Weibenfalk上的Youtube，
Weibenfalk 课程网站。

**Comment by miyaliu666** [comment]
谢谢 @suiboyu 翻译本文，我才看到这个评论。
你可以参照 readme 里面的[图文详解如何参与翻译](https://github.com/freeCodeCamp/news-translation/blob/master/Contributing.md) 所写的流程 pull request 吗？
如果有什么问题，可以在这里留言跟我说，或者加我微信 Hello_MrT 即时沟通。

**Comment by miyaliu666** [comment]
@suiboyu 你好，如果你对翻译流程不太清楚的话，欢迎参加我们本周六下午 1 点 - 3 点的在线翻译工作坊。
可以加我微信 Hello_MrT 具体交流哈：）
