### ISSUE TITLE
帮助初级开发者提升自己的 9 个好习惯

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#300]
- 原文网址：[9 Habits I Wish I Had as a Junior Developer](https://www.freecodecamp.org/news/good-habits-for-junior-developers/)
- MarkDown 文件：https://github.com/freeCodeCamp/chinese/blob/main/chinese/articles/good-habits-for-junior-developers.md

**Comment by Chen-Shuijiao** [comment]
翻譯認領

**Comment by miyaliu666** [comment]
@Chen-Shuijiao 已经修改标签为 `Translation-in-progress`。谢谢参加翻译协作：）

**Comment by Tsukistar** [comment]
The markdown file is "not found" now. I'm interested in it and I want to translate it in the next week.

**Comment by miyaliu666** [comment]
@Tsukistar Great! I'll close this issue and create another one, so you can translate it. Thank you. Happy contributing!

**Comment by miyaliu666** [comment]
@Tsukistar 好的，谢谢参与翻译。

@stevending1st @luojiyin1987 可以帮忙看一下这个 issue 吗？这是我之前创建的，markdown 文件不能打开。我刚才关闭了这个 issue，重新创建 issue，提醒说重复了。被关闭的 issue 是否应该不影响重新创建的呢？

**Comment by luojiyin1987** [comment]
@miyaliu666  原来的项目名是 news-translation  现在改成了 chinese，所以找不到了。

**Comment by miyaliu666** [comment]
> @miyaliu666 原来的项目名是 news-translation 现在改成了 chinese，所以找不到了。

明白了，我现在替换了新的链接，可以翻译了，谢谢提醒。
