### ISSUE TITLE
在 freeCodeCamp 学习编程，我从土建工程师转行成为 Web 开发者

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#331]
- 原文网址：[How I Went from Civil Engineer to Web Developer Using freeCodeCamp to Learn to Code](https://www.freecodecamp.org/news/from-civil-engineer-to-web-developer-with-freecodecamp/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/from-civil-engineer-to-web-developer-with-freecodecamp.md

**Comment by herosql** [comment]
@miyaliu666 这篇好像被[newdegen](https://github.com/newdegen)翻完了

**Comment by miyaliu666** [comment]
是的，这篇文章的[中文版](https://www.freecodecamp.org/chinese/news/from-civil-engineer-to-web-developer-with-freecodecamp/)已经发布了，我现在关闭 issue，谢谢！
