### ISSUE TITLE
SQL 注入教程——什么是 SQL 注入以及如何防止它

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#383]
- 原文网址：[SQL Injection Tutorial - What is SQL Injection and How to Prevent it](https://www.freecodecamp.org/news/what-is-sql-injection-how-to-prevent-it/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/what-is-sql-injection-how-to-prevent-it.md

**Comment by herosql** [comment]
@miyaliu666 这篇已经翻译
