### ISSUE TITLE
/learn 页面的名言和课程里的激励语句

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#402]
- 原文：https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/chinese/motivation.json

需要翻译[这个页面](https://chinese.freecodecamp.org/learn/)随机产生的名言，例如：

![image](https://user-images.githubusercontent.com/19358186/112328972-be247780-8cf1-11eb-9228-42f0d6b4fe6a.png)

以及通过一道挑战后显示的激励语，例如：

![image](https://user-images.githubusercontent.com/19358186/112329432-283d1c80-8cf2-11eb-89fc-1ac3da48bd88.png)

名言应该好翻译一些，比如爱因斯坦的名言一般都有对应的中文翻译。除了翻译，我们也可以增加一些中文原创的名言，比如：不积跬步无以至千里。

激励语可能不好翻译，那么我们可以直接改成中文原创的激励语。

我建议大家在这个 issue 下面评论，把自己的译文或者建议的原创中文句子写下来，然后我结合大家的建议提交一个 PR。

谢谢！

**Comment by leonfeng** [comment]
WIP: https://github.com/leonfeng/freeCodeCamp/commit/9d9e6a5767aad4f4bdc0b67e5f3d80ad9048156e?branch=9d9e6a5767aad4f4bdc0b67e5f3d80ad9048156e&diff=split

敬请评论、纠正 👩‍🏫
