### ISSUE TITLE
[Auto] 使用网页设计基本原则，让你的网站更美观

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#420]
- 原文网址：[How to Use Basic Web Design Principles to Make Your Site Beautiful](https://www.freecodecamp.org/news/make-your-site-beautiful-using-web-design-principles/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/make-your-site-beautiful-using-web-design-principles.md

**Comment by herosql** [comment]
@miyaliu666 MarkDown 文件404,找不到

**Comment by miyaliu666** [comment]
@herosql 那我把这个 issue 关掉吧，重新创建看看

**Comment by luojiyin1987** [comment]
原来就没生成 markdown 文件成功
