### ISSUE TITLE
[Auto] 演化博弈论简介

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#432]
- 原文网址：[Introduction to Evolutionary Game Theory](https://www.freecodecamp.org/news/introduction-to-evolutionary-game-theory/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/introduction-to-evolutionary-game-theory.md

**Comment by Shenghan0329** [comment]
I want to claim this issue. I've started working on the translation.

**Comment by Shenghan0329** [comment]
@miyaliu666 Hi, I've finished the translation on this article. : )
