### ISSUE TITLE
[Auto] 如何通过可持续的小习惯获得你的第一份开发工作

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#465]
- 原文网址：[How to Use Small and Sustainable Habits to Get Your First Dev Job](https://www.freecodecamp.org/news/how-to-use-small-sustainable-habits-to-get-your-first-dev-job/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-use-small-sustainable-habits-to-get-your-first-dev-job.md

**Comment by luojiyin1987** [comment]
我来翻译  @miyaliu666

**Comment by miyaliu666** [comment]
@luojiyin1987 好的，已经修改了标签，你可以直接 PR 了，谢谢

**Comment by luojiyin1987** [comment]
#562
