### ISSUE TITLE
[Auto] 斯科菲尔德定律

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#472]
- 原文网址：[Schofield's Laws of Computing – What they Are and Why You Should Know Them](https://www.freecodecamp.org/news/schofields-laws-of-computing/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/schofields-laws-of-computing.md

**Comment by luojiyin1987** [comment]
我来翻译 @miyaliu666

**Comment by luojiyin1987** [comment]
已经翻译完了。
