### ISSUE TITLE
[Auto] 用 React 创建一个作品集网站

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#493]
- 原文网址：[How to Build a Portfolio Website with React](https://www.freecodecamp.org/news/build-portfolio-website-react/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/build-portfolio-website-react.md

**Comment by luojiyin1987** [comment]
我来翻译吧。 @miyaliu666

**Comment by luojiyin1987** [comment]
#564
