### ISSUE TITLE
[Auto] 如何使用 Python、Numpy、Pandas、Matplotlib 和 Seaborn 可视化数据

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#498]
- 原文网址：[What is Data Analysis? How to Visualize Data with Python, Numpy, Pandas, Matplotlib & Seaborn Tutorial](https://www.freecodecamp.org/news/exploratory-data-analysis-with-numpy-pandas-matplotlib-seaborn/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/exploratory-data-analysis-with-numpy-pandas-matplotlib-seaborn.md

**Comment by ZhichengChen** [comment]
repeat with #506
