### ISSUE TITLE
[Auto] CSS 布局属性

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#500]
- 原文网址：[How the CSS Position Property Works – Explained with Code Examples](https://www.freecodecamp.org/news/css-position-property-explained/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/css-position-property-explained.md

**Comment by herosql** [comment]
@miyaliu666 这篇已经被翻译了,
![Screenshot from 2023-08-01 16-49-58](https://github.com/freeCodeCamp/chinese/assets/39084622/0113df5b-05ed-442c-b320-29a9993e4747)

**Comment by miyaliu666** [comment]
@herosql  谢谢提醒，这篇的[中文版](https://www.freecodecamp.org/chinese/news/css-position-property-explained/)也已经发布了。我在跟踪 issue 和 PR 这方面做得不及时。译文基本上都已经发布了，有些 PR 还没关，会尽快处理。
