### ISSUE TITLE
[Auto] 用 Python、Numpy、Pandas、Matplotlib & Seaborn 可视化数据

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#506]
- 原文网址：[What is Data Analysis? How to Visualize Data with Python, Numpy, Pandas, Matplotlib & Seaborn Tutorial](https://www.freecodecamp.org/news/exploratory-data-analysis-with-numpy-pandas-matplotlib-seaborn/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/exploratory-data-analysis-with-numpy-pandas-matplotlib-seaborn.md

**Comment by seanbei** [comment]
我看原文中是有代码示例的，但是此Markdown文件中并没有相关信息，应该怎么插入代码呢？ @miyaliu666

**Comment by miyaliu666** [comment]
> 我看原文中是有代码示例的，但是此Markdown文件中并没有相关信息，应该怎么插入代码呢？ @miyaliu666

你翻译的时候不管吧，我在正式发布文章的时候再加入链接。
