### ISSUE TITLE
[Auto] 如何使用 GitHub Actions 将 Next.js 网站部署到 AWS S3

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#508]
- 原文网址：[How to Use Github Actions to Deploy a Next.js Website to AWS S3](https://www.freecodecamp.org/news/how-to-use-github-actions-to-deploy-a-next-js-website-to-aws-s3/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-use-github-actions-to-deploy-a-next-js-website-to-aws-s3.md

**Comment by luojiyin1987** [comment]
我来翻译  @miyaliu666

**Comment by luojiyin1987** [comment]
#567

**Comment by luojiyin1987** [comment]
@miyaliu666  可以关闭了
