### ISSUE TITLE
[Auto] 使用 Next.js 和 Supabase 进行全栈开发

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#509]
- 原文网址：[Full Stack Development with Next.js and Supabase – The Complete Guide](https://www.freecodecamp.org/news/the-complete-guide-to-full-stack-development-with-supabas/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/the-complete-guide-to-full-stack-development-with-supabas.md

**Comment by luojiyin1987** [comment]
我来翻译 @miyaliu666

**Comment by luojiyin1987** [comment]
#578

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成
