### ISSUE TITLE
[Auto] React 18 有什么新特性？

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#512]
- 原文网址：[What's New in React 18? Concurrency, Batching, the Transition API and More](https://www.freecodecamp.org/news/whats-new-in-react-18/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/whats-new-in-react-18.md

**Comment by luojiyin1987** [comment]
我来翻译  @miyaliu666

**Comment by luojiyin1987** [comment]
#577
