### ISSUE TITLE
[Auto] 通过构建 5 个响应式布局来学习 CSS Flexbox

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#516]
- 原文网址：[Learn CSS Flexbox by Building 5 Responsive Layouts](https://www.freecodecamp.org/news/learn-flexbox-build-5-layouts/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/learn-flexbox-build-5-layouts.md

**Comment by miyaliu666** [comment]
@Miever1 assignees 那里我没法 assign 给你，所以艾特你了

**Comment by Miever1** [comment]
todo
