### ISSUE TITLE
[Auto] 通过构建三个项目来学习 CSS 媒体查询

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#517]
- 原文网址：[Learn CSS Media Queries by Building Three Projects](https://www.freecodecamp.org/news/learn-css-media-queries-by-building-projects/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/learn-css-media-queries-by-building-projects.md

**Comment by miyaliu666** [comment]
@Miever1

**Comment by Miever1** [comment]
todo
