### ISSUE TITLE
[Auto] 带有 Flexbox 属性备忘单的 CSS Flexbox 教程 🎖️

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#518]
- 原文网址：[CSS Flexbox Tutorial with Flexbox Properties Cheat Sheet 🎖️](https://www.freecodecamp.org/news/css-flexbox-tutorial-with-cheatsheet/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/css-flexbox-tutorial-with-cheatsheet.md

**Comment by miyaliu666** [comment]
@Miever1

**Comment by Miever1** [comment]
todo
