### ISSUE TITLE
[Auto] 如何使用 Flexbox 和 Grid 在 CSS 中居中 ✨

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#520]
- 原文网址：[How to Center Anything in CSS Using Flexbox and Grid ✨](https://www.freecodecamp.org/news/how-to-center-objects-using-css/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/how-to-center-objects-using-css.md

**Comment by miyaliu666** [comment]
@Miever1

**Comment by Miever1** [comment]
todo
