### ISSUE TITLE
[Auto] JavaScript 模块

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#522]
- 原文网址：[JavaScript Modules – Explained with Examples](https://www.freecodecamp.org/news/javascript-modules-explained-with-examples/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/javascript-modules-explained-with-examples.md

**Comment by luojiyin1987** [comment]
@miyaliu666    这个已经有人翻译好了， 是否要关闭？

**Comment by miyaliu666** [comment]
@luojiyin1987 [这篇](https://chinese.freecodecamp.org/news/javascript-modules-explained-with-examples/)已经发布了。等我把 PR 全部理一遍然后关闭吧，谢谢提醒。
