### ISSUE TITLE
[Auto] HTML Button onclick – JavaScript 点击事件教程

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#540]
- 原文网址：[HTML Button onclick – JavaScript Click Event Tutorial](https://www.freecodecamp.org/news/html-button-onclick-javascript-click-event-tutorial/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/html-button-onclick-javascript-click-event-tutorial.md

**Comment by luojiyin1987** [comment]
我来认领  @miyaliu666
