### ISSUE TITLE
[Auto] Python 读取 JSON 文件——如何从文件加载 JSON

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#546]
- 原文网址：[Python Read JSON File – How to Load JSON from a File and Parse Dumps](https://www.freecodecamp.org/news/python-read-json-file-how-to-load-json-from-a-file-and-parse-dumps/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/python-read-json-file-how-to-load-json-from-a-file-and-parse-dumps.md

**Comment by AbbetWang** [comment]
I wanna translate it.

**Comment by miyaliu666** [comment]
@AbbetWang 已经修改标签为翻译中，你可以根据 readme 中的图文指南 pull request 啦，谢谢！
