### ISSUE TITLE
[Auto]（如何寻找在家远程工作的机会）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/chinese#601]
- 原文网址：[Remote Work – How to Find Remote Working Jobs from Home](https://www.freecodecamp.org/news/remote-work-how-to-find-remote-working-jobs-from-home/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/remote-work-how-to-find-remote-working-jobs-from-home.md

**Comment by luojiyin1987** [comment]
#602

**Comment by miyaliu666** [comment]
你最近完成了好多翻译啊！！

**Comment by luojiyin1987** [comment]
只是我最近找远程工作，看看国外的人怎么做的。
