### ISSUE TITLE
[Auto]（JSON Stringify 示例——如何用 JS 解析 JSON 对象）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#622]
- 原文网址：[JSON Stringify Example – How to Parse a JSON Object with JS](https://www.freecodecamp.org/news/json-stringify-example-how-to-parse-a-json-object-with-javascript/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/json-stringify-example-how-to-parse-a-json-object-with-javascript.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译

**Comment by luojiyin1987** [comment]
@miyaliu666   翻译完了
