### ISSUE TITLE
[Auto]（Git Pull Force——如何用 Git 覆盖本地更改）

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#624]
- 原文网址：[Git Pull Force – How to Overwrite Local Changes With Git](https://www.freecodecamp.org/news/git-pull-force-how-to-overwrite-local-changes-with-git/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/git-pull-force-how-to-overwrite-local-changes-with-git.md

**Comment by luojiyin1987** [comment]
@miyaliu666   我来翻译吧

**Comment by luojiyin1987** [comment]
#634    @miyaliu666   已经翻译完
