### ISSUE TITLE
[Auto]（在线编程课程 - 初学者[2022年指南]）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/chinese#627]
- 原文网址：[online-coding-classes-for-beginners-2022-guide](https://www.freecodecamp.org/news/online-coding-classes-for-beginners-2022-guide/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/online-coding-classes-for-beginners-2022-guide.md

**Comment by luojiyin1987** [comment]
@miyaliu666  翻译完成

**Comment by luojiyin1987** [comment]
已经对 目录中跳转修改完了，没进行验证， 感觉大部分不会生效。不过如果读者会用查找，问题不大。

再吐槽一下  原文中 没有  `godot-game-engine-tutorial-make-a-2d-platformer-game` 相关具体内容。

@miyaliu666

**Comment by miyaliu666** [comment]
好的，已在专栏更新，等页面显示了看看是否生效吧，辛苦了
