### ISSUE TITLE
[Auto]（前端与后端--有什么区别？）

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/chinese#651]
- 原文网址：[frontend-vs-backend-whats-the-difference](https://www.freecodecamp.org/news/frontend-vs-backend-whats-the-difference/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/frontend-vs-backend-whats-the-difference.md

**Comment by luojiyin1987** [comment]
@miyaliu666    已经翻译完了。 不过原作者写得比较随意

**Comment by miyaliu666** [comment]
> @miyaliu666 已经翻译完了。 不过原作者写得比较随意

如果你有兴趣，可以就这个主题写一篇更详细的原创文章
