### ISSUE TITLE
The Coding Bootcamp Handbook: How Do Bootcamps Work and Are They Right for You?

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#67]
文章：[The Coding Bootcamp Handbook: How Do Bootcamps Work and Are They Right for You?](https://www.freecodecamp.org/news/coding-bootcamp-handbook/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/coding-bootcamp-handbook.md)
PR 地址：

**Comment by miyaliu666** [comment]
这是一篇值得精读的文章，作者：Quincy Larson，freeCodeCamp 创始人

**Comment by qiqicodes** [comment]
I would like to work on this, thank you!
