### ISSUE TITLE
[Auto]（React 文档）

### ISSUE THREAD

**Issue by webVueBlog** [freeCodeCamp/chinese#811]
- 原文网址：[[原文标题](https://www.freecodecamp.org/news/路由/)](https://learn-docs.github.io/learn-React/)
- MarkDown 文件：https://github.com/learn-docs/learn-React#readme

**Comment by miyaliu666** [comment]
你好，谢谢添加 issue！

我们在这个仓库只翻译 freeCodeCamp 专栏的文章哦，所以你会看到以上 action 报错。

如果你想在[中文专栏](https://chinese.freecodecamp.org/news)发布文章，可以先联系我获得 邀请注册作者账号的链接。

然后，如果你希望把这篇文章翻译成英文，发布在[英文专栏](https://www.freecodecamp.org/news/)，可以稍后以中文专栏的文章来发 issue。

（此外，翻译贡献者们是自发认领翻译任务，所以我们不确定最近是否有贡献者会认领翻译这篇文章为英文。）

对于这个 issue，也是一样的 #812

**Comment by miyaliu666** [comment]
我们现在不能手动添加 issue 啦？

@luojiyin1987 @stevending1st

**Comment by stevending1st** [comment]
> 我们现在不能手动添加 issue 啦？只能使用 action 了吗？
> 
> @luojiyin1987 @stevending1st

应该可以手动添加啊

**Comment by luojiyin1987** [comment]
什么叫 手动添加？  @miyaliu666 
现在是从模板里选 两种类型。

**Comment by miyaliu666** [comment]
好的好的，我理解了，谢谢两位 @luojiyin1987 @stevending1st
