### ISSUE TITLE
[Auto]（面向初学者的统计学--进入数据科学领域前需要了解的顶级统计学概念）

### ISSUE THREAD

**Issue by Gradonlee** [freeCodeCamp/chinese#859]
- 原文网址：[Statistics for Beginners – Top Stats Concepts to Know Before Getting into Data Science](https://www.freecodecamp.org/news/top-statistics-concepts-to-know-before-getting-into-data-science/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/blob/main/chinese/articles/top-statistics-concepts-to-know-before-getting-into-data-science.md

**Comment by suntarliarzn** [comment]
这篇有人翻译吗？如果没有，我就领取了哦

**Comment by Gradonlee** [comment]
你翻译吧，最近太忙了，没时间翻译，不好意思

Chencheng Li

**Comment by suntarliarzn** [comment]
已完成翻译@miyaliu666
