### ISSUE TITLE
How to write a killer Software Engineering résumé

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/chinese#87]
文章：[How to write a killer Software Engineering résumé](https://www.freecodecamp.org/news/writing-a-killer-software-engineering-resume-b11c91ef699d/)
认领 Markdown 文件：[文件地址](https://github.com/freeCodeCamp/news-translation/blob/master/chinese/articles/writing-a-killer-software-engineering-resume.md)
PR 地址：

**Comment by LolaWei** [comment]
认领校对

**Comment by LolaWei** [comment]
校对完成...但我不知道自己的操作正不正确....不好意思github用的还不是太熟==

**Comment by miyaliu666** [comment]
没有看到你的校对意见耶，你可以加我微信说一下吗？Hello_MrT。
谢谢！
