### ISSUE TITLE
[Auto]（统计入门 - 尝试数据科学之前一定要掌握的重要统计学概念）

### ISSUE THREAD

**Issue by toudatouda** [freeCodeCamp/chinese#883]
- 原文网址：[Statistics for Beginners – Top Stats Concepts to Know Before Getting into Data Science](https://www.freecodecamp.org/news/top-statistics-concepts-to-know-before-getting-into-data-science/)
- MarkDown 文件：https://github.com/freeCodeCamp/news-translation/edit/main/chinese/articles/top-statistics-concepts-to-know-before-getting-into-data-science.md

**Comment by HeZean** [comment]
Hi, I'm willing to work on it!

**Comment by HeZean** [comment]
Hi, it seems to be a dup of #859?

**Comment by toudatouda** [comment]
Good day
It seems someone has already working on it, but Im not so sure


| |
Liu Hesheng
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Chris ***@***.***> |
| 发送日期 | 2022年8月7日 22:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [freeCodeCamp/news-translation] [Auto]（统计入门 - 尝试数据科学之前一定要掌握的重要统计学概念） (Issue #883) |

Hi, it seems to be a dup of #859?

**Comment by HeZean** [comment]
#860 is wip
